import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export enum Controls {
  forward = 'forward',
  back = 'back',
  left = 'left',
  right = 'right',
  jump = 'jump',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
        <body
          className={`${inter.variable} antialiased bg-green-500 text-gray-700`}
          >
            <header className={"sticky z-10 p-8 h-10 w-full space-x-10 flex flex-row"}>
                    <Link href={"/"} className={"text-lg md:w-1/2 md:text-4xl"}>{"Ben Papac"}</Link>
                    <div className={"flex flex-row space-x-10 place-content-end md:w-1/2"}>
            
                      <Link href={"/contact"}>{"Contact"}</Link>
                      <Link href={'/benpapac_resume.pdf'} 
                      target='_blank' 
                      rel='noreferrer noopener'
                      >
                        {"Resume"}
                    </Link>
                        </div>
                  </header>
          {children}
        </body>
    </html>
  );
}
